Sprint3/step1
bn-ilya/react-burger pull request #6
Opened 2023-09-07 22:39 UTC by bn-ilya

2023-09-08 05:23 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть автологин
- Показываете ошибку пользователю
- Есть механизм обновления токена

Необходимо исправить:
- Если в хранилище нет токена, то делать запрос данных юзера нет смысла

**Можно лучше**
- При клике на лого обычно следует делать переход на главную страницу

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-08 05:23 UTC, andryxxa93 commented on src/components/routes-app/routes-app.js
> +                <Route path='/login' element={<ProtectedRouteElement element={<LoginPage />} accessAuth={false} />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-09-08 05:23 UTC, andryxxa93 commented on src/utils/burger-api.js
> +export const forgotPassword = (email) => {
**Можно лучше**
Чтобы не дублировать в каждом запросе проверки на ok  и success можно создать функцию request. Которая будет принимать в качестве параметров url и опции запроса. В ней уже будут обе проверки на success и ok. Нужно только заменить все fetch на эту функцию.

2023-09-08 05:23 UTC, andryxxa93 commented on src/pages/login-page/main/login-form/login-form.js
> +            location?.state?.goBack ? navigate(location.state.goBack.pathname, { replace: true }) : navigate('/', { replace: true })
**Можно лучше**
По хорошему данную логику должен выполнять ProtectedRouteElement. Надо только записывать в background нужное значение.

2023-09-08 15:35 UTC, bn-ilya commented on src/pages/login-page/main/login-form/login-form.js
> +            location?.state?.goBack ? navigate(location.state.goBack.pathname, { replace: true }) : navigate('/', { replace: true })
Извините, не пойму как это сделать. Что тогда должно происходить после dispatch? Он же должен сделать куда-то переход?

2023-09-09 05:30 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-24 16:08 UTC, merged